import { Inter, Noto_Serif_SC } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const inter = Noto_Serif_SC({subsets: ['latin'], weight: '500'})

export const metadata = {
  title: "Nextjs Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
